### ISSUE TITLE
При запуске main.lua вываливает без остановки кучу OnParam

### ISSUE THREAD

**Issue by euvgub** [DmitryPukhov/pytrade#1]
При запуске main.lua до авторизации и после авторизации message:{"id": 1, "method": "checkSecurity", "args": ["1"]}
вываливает по кругу без остановки кучу OnParam типа такого:
message:{"id":"callback","result":{"class_code":"SPBFUT","sec_code":"RNH9"},"callback_name":"OnParam"}message:{"id":"callback","result":{"class_code":"SPBFUT","sec_code":"RNH9"},"callback_name":"OnParam"}message:{"id":"callback","result":{"class_code":"SPBFUT","sec_code":"SiH9"},"callback_name":"OnParam"}message:{"id":"callback","result":{"class_code":"SPBFUT","sec_code":"GDH9"},"callback_name":"OnParam"}message:{"id":"callback","result":{"class_code":"SPBFUT","sec_code":"EuH9"},"callback_name":"OnParam"}message:{"id":"callback","result":{"class_code":"SPBFUT","sec_code":"MXH9"},"callback_name":"OnParam"}message:{"id":"callback","result":{"class_code":"SPBFUT","sec_code":"EDH9"},"callback_name":"OnParam"}

**Comment by DmitryPukhov** [comment]
Switched to WebQuik instead of desktop Quik+lua, so no lua errors anymore.
