### ISSUE TITLE
Your local changes to pytrade/Config.py would be overwritten by merge

### ISSUE THREAD

**Issue by dsultanr** [DmitryPukhov/pytrade#12]
git pull throws error:

```
From https://github.com/DmitryPukhov/pytrade
   7c220e7..7d74e9e  master            -> origin/master
 * [new branch]      feature/www-react -> origin/feature/www-react
Updating 7c220e7..7d74e9e
error: Your local changes to the following files would be overwritten by merge:
        pytrade/Config.py
Please commit your changes or stash them before you merge.

```

any thoughts how to manage coexistence of local config and repo's?

**Comment by dsultanr** [comment]
forced to update from repo, noted that config file is moved to app.yaml

anyway we need to manage this

[here is the best practice advice on config files in repo](https://stackoverflow.com/a/9343239)

I think it's a very good idea

**Comment by DmitryPukhov** [comment]
Thank you for the advice, I redesigned the configuration according to best practices from your link. app.yaml is a local config now and in .gitignore.
