### ISSUE TITLE
Separate branches

### ISSUE THREAD

**Issue by dsultanr** [DmitryPukhov/pytrade#16]
Could you plase create different branches for versions? with RabbitMQ/UI and without? or maybe even without Docker
Actually I don't need UI for now

does this [commit ](https://github.com/DmitryPukhov/pytrade/commit/ee11cabc4f3546a507e2ee781c2c6d05e1e95432) is a checkpoint on huge upgrade?

**Comment by DmitryPukhov** [comment]
Yes, that commit, but I think no need to roll back because I added ability to turn Rabbit off. If **is_interop=False** in app.yaml, Rabbit is not used and the app will work as before.
