### ISSUE TITLE
DEBUG WebQuikConnector - _on_message: Got msg {"msgid":20001,"auth_type":3,"min_available_length":1,"max_available_length":32,"is_alphanumeric":1,"pin_mode":65}

### ISSUE THREAD

**Issue by euvgub** [DmitryPukhov/pytrade#3]
Отключить sms авторизацию брокер не дает. Как отловить в каком виде послать полученный pin код?
С помощью wsdump.py из websocket-client не удается поймать, как отсылается pin code
DEBUG WebQuikConnector - _on_message: Got msg {"msgid":20001,"auth_type":3,"min_available_length":1,"max_available_length":32,"is_alphanumeric":1,"pin_mode":65}

```
if msgid == '20001':
    pin_code = input("Enter the PIN code: ")
    self.websocket_app.send('{"???pin???":%s}' % pin_code)
```

**Comment by euvgub** [comment]
Ответ: Chrome DevTools или Fiddler
--> {"msgid":10000,"classes":[],"login":"your_login","password":"your_password","btc":"true","width":"1366","height":"486","compressed":"deflate","app_type":"WEB","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36","lang":"ru","sid":"54628.33333398","version":"7.2.0","device_desc":"SYSTEM=Win32%%OS-VERSION=%%LOCAL_TIME=Среда 2020-07-29 10:55:03.120 GMT+03:00%%USER_LOCAL_INFO=en"}
--> {"msgid":10008}
<-- {"msgid":20008,"resultCode":1,"time":"0-00-00 10:55:01"}
<-- {"msgid":20006,"resultCode":0,"authMode":4,"serverMessage":"Соединение установлено"}
<-- {"msgid":20014,"datetime":"2020-07-29 10:55:02","text":"Соединение установлено"}
<-- {"msgid":20004,"message":"Введите PIN"}
<-- {"msgid":20001,"auth_type":3,"min_available_length":1,"max_available_length":32,"is_alphanumeric":1,"pin_mode":65}
--> {"msgid":10008}
<-- {"msgid":20008,"resultCode":1,"time":"0-00-00 10:55:04"}
...
...
...
<-- {"msgid":20008,"resultCode":1,"time":"0-00-00 10:55:31"}
--> {"msgid":10001,"pin":"72846"}
--> {"msgid":10008}
<-- {"msgid":20004,"message":"Двухфакторная аутентификация прошла успешно"}
<-- {"msgid":20000,"resultCode":0,"tradeSession":{"id":"xxxx-0000-xxxx-a46d-xxxxxxxxxx","flags":0,"date":20200729},"classList":[],"uid":xxxxxx,"userProperties":{"qLang":"ru","panels":[{"title":"Si-9.20 [FORTS]","manualHeight":700,"collapsed":false, ................
........
.......
.......
<--{"msgid":21003,"number":26152055889537,"ccode":"SPBFUT","scode":"SiU0","qdate":20200728,"qtime":192630,"n_order":26152056258788,"sell":1,"account":"xxxxxx","price":72830,"qty":24,"volume":174792000,"ucode":"xxxxxx","code":"","yield":0,"accr":0,"refer":"","firm":"xxxxxxxxx","price_currency":"SUR","settle_currency":"","broker_comission":0}

**Comment by DmitryPukhov** [comment]
Thanks for figuring this out!
