### ISSUE TITLE
PING/PONG heartbeat messages 

### ISSUE THREAD

**Issue by euvgub** [DmitryPukhov/pytrade#5]
PING/PONG heartbeat messages 
from client {"msgid":10008}
from server  {"msgid":20008,"resultCode":1,"time":"x-xx-xx xx:xx:xx"}

**Comment by AndersenInc** [comment]
Добрый день. Скажите пожалуйста, где вы нашли все эти коды:
Есть ли какая то документация для сервера webquik? 
    """
    Message id constants
    """
    # Responce codes starts from 2 {mapIdName:{20000:"Авторизация",20001:"Запрос PIN",20002:"Ответ на запрос длины
    # пароля",20003:"Ответ на запрос смены пароля",20004:"Сообщения авторизации",20005:"Результат сохранения
    # профиля",20008:"Статус соединения",20014:"Сообщения сервера",21000:"Классы",21001:"Заявки",21003:"Сделки",
    # 21004:"Денежн.лимиты",21005:"Бумаж.лимиты",21006:"Ограничения",21007:"Позиции",21008:"Сообщения брокера",
    # 21009:"Ответы на транзакции",21011:"Основные торги",21011:"Торги для ТТП",21012:"Купить/Продать",
    # 21013:"Портфель",21014:"Стаканы",21015:"Ответ по RFS",21016:"Графики",21017:"Новости",21018:"Тексты новостей",
    # 21019:"Валютные пары",21020:"Инфо по бумаге",21021:"Котировки RFS",21022:"Торговые счета",21023:"Торги по
    # вал.парам",21024:"Список вал.пар",22000:"Ответ по заявке",22001:"Ответ по стоп-заявке",22002:"Ответ по
    # связ.стоп-заявке",22003:"Ответ по услов.стоп-заявке",22004:"Ответ по FX-заявке",22100:"Ответ по снятию заявки",
    # 22101:"Ответ по снятию стоп-заявки"},

**Comment by euvgub** [comment]
https://junior.webquik.ru/classes/controller/CtrlWSocket.js

**Comment by AndersenInc** [comment]
Большое спасибо. То, что нужно

ср, 16 дек. 2020 г. в 15:30, euvgub <notifications@github.com>:

**Comment by slukin1** [comment]
com.arqa.quikandroidx.apk/sources/Core/DataLayer/Data/MsgInId.java
com.arqa.quikandroidx.apk/sources/Core/DataLayer/Data/MsgOutId.java

public final class MsgInId {
    public static final int AddClasses = 21000;
    public static final int AnsMarketToLimitPrice = 29001;
    public static final int AnsQmarginParameter = 29002;
    public static final int AnsSecurityRestrictionIntervals = 29002;
    public static final int AnswerInitInstrPlugin = 21090;
    public static final int AnswerInstrCancelReasons = 21097;
    public static final int AnswerInstrConfirmOTPResult = 21099;
    public static final int AnswerInstrNeedConfirmOTP = 21098;
    public static final int AnswerInstrNoteClientData = 21094;
    public static final int AnswerInstrNoteFormOptions = 21095;
    public static final int AskPin = 20001;
    public static final int AuthAnswer = 20006;
    public static final int AuthMessage = 20004;
    public static final int AuthResult = 20000;
    public static final int BrokerMsg = 21008;
    public static final int BuySell = 21012;
    public static final int CalcComissionResult = 23005;
    public static final int ClassesSent = 26000;
    public static final int CurData = 21011;
    public static final int DemoAnswer = 13012;
    public static final int DepoLimit = 21005;
    public static final int FutHolding = 21007;
    public static final int FutLimit = 21006;
    public static final int Graph = 21016;
    public static final MsgInId INSTANCE = new MsgInId();
    public static final int InstrNewMonResult = 21092;
    public static final int Instruction = 21091;
    public static final int InvestIdeasAnswer = 21061;
    public static final int InvestInstrumentsAnswer = 21060;
    public static final int LimitHasReceived = 21063;
    public static final int LinkStatusRes = 20008;
    public static final int MoneyLimit = 21004;
    public static final int NegDealOrder = 21025;
    public static final int NewOrderResult = 22000;
    public static final int NewPasswordPinAnswer = 13201;
    public static final int NewStopOrderResult = 22001;
    public static final int News = 21017;
    public static final int NewsBody = 21018;
    public static final int NotificationPushReport = 22401;
    public static final int NotificationSettingsAnswer = 21082;
    public static final int NotificationStartAnswer = 21081;
    public static final int Order = 21001;
    public static final int Portfolio = 21013;
    public static final int PswRecovery = 20020;
    public static final int QMonitorMessage = 20015;
    public static final int Quotes = 21014;
    public static final int RegistrationFormAnswer = 13011;
    public static final int RemoveInvestIdeas = 21065;
    public static final int RequestPasswordAnswer = 13101;
    public static final int ReviewPDF = 21064;
    public static final int SecInfo = 21020;
    public static final int ServerMessage = 20014;
    public static final int SettingsFilesAnswer = 21101;
    public static final int StopOrder = 21002;
    public static final int Trade = 21003;
    public static final int Traders = 26001;
    public static final int TranResult = 21009;
    public static final int TrdAcc = 21022;
    public static final int UserProfileAnswer = 21062;

public final class MsgOutId {
    public static final int Anketa = 13001;
    public static final int Ask2FA = 13003;
    public static final int AskCalcBuysell = 13004;
    public static final int AskCalcComission = 13005;
    public static final int AskCancelReasons = 11097;
    public static final int AskDenyInstruction = 11093;
    public static final int AskInitInstrPlugin = 11090;
    public static final int AskInstrConfirmOTP = 11099;
    public static final int AskInstrNoteClientData = 11094;
    public static final int AskInstrNoteFormOptions = 11095;
    public static final int AskInstrOTP = 11098;
    public static final int AskInstructions = 11091;
    public static final int AskInvestIdeas = 11061;
    public static final int AskInvestInstruments = 11060;
    public static final int AskMarketToLimitPrice = 19001;
    public static final int AskQmarginParameter = 19002;
    public static final int BrokerMessageAnswer = 11008;
    public static final int BrokerMessageDelivered = 11009;
    public static final int BuySellStart = 11012;
    public static final int BuySellStop = 11112;
    public static final int CurDataStart = 11011;
    public static final int CurDataStop = 11111;
    public static final int DemoReq = 13002;
    public static final int Disconnect = 10006;
    public static final int Error = 10007;
    public static final int GetReviewPDF = 11064;
    public static final MsgOutId INSTANCE = new MsgOutId();
    public static final int Login = 10000;
    public static final int NegDealKill = 12102;
    public static final int NewInstruction = 11096;
    public static final int NewOrder = 12000;
    public static final int NewPasswordPin = 13200;
    public static final int NewStopOrder = 12001;
    public static final int NewsBodyRequest = 11018;
    public static final int NewsStart = 11017;
    public static final int NewsStop = 11117;
    public static final int NotificationAskPushReport = 12401;
    public static final int NotificationKill = 11085;
    public static final int NotificationSet = 11084;
    public static final int NotificationSettingsRequest = 11082;
    public static final int NotificationSettingsSet = 11083;
    public static final int NotificationStart = 11081;
    public static final int OrderKiller = 12100;
    public static final int PinAnswer = 10001;
    public static final int Ping = 10008;
    public static final int PortfolioStart = 11013;
    public static final int ProfileSaveReq = 10005;
    public static final int PswRecoveryUserData = 10020;
    public static final int QMarginParams = 10010;
    public static final int RequestPassword = 13100;
    public static final int SecInfoRequest = 11020;
    public static final int SettingsFiles = 11101;
    public static final int StartGraph = 11016;
    public static final int StartQuote = 11014;
    public static final int StopGraph = 11116;
    public static final int StopOrderKiller = 12101;
    public static final int StopQuote = 11114;
    public static final int TradersReq = 16001;
