### ISSUE TITLE
ModuleNotFoundError: No module named 'pytrade'

### ISSUE THREAD

**Issue by dsultanr** [DmitryPukhov/pytrade#7]
```
# git clone https://github.com/DmitryPukhov/pytrade.git
# cd pytrade/pytrade
# python App.py
Traceback (most recent call last):
  File "/mnt/talib/pytrade/pytrade/App.py", line 7, in <module>
    from pytrade.feed.Feed2Csv import Feed2Csv
ModuleNotFoundError: No module named 'pytrade'

```

теперь такая ошибка

**Comment by dsultanr** [comment]
скопировал папку pytrade внутрь pytrade, запустилось, но теперь другая ошибка:

```

Enter q for quit, b for buy or s for sell:2021-03-10 10:20:35.792 INFO WebQuikConnector - run: Connecting to wss://webquik.sberbank.ru:443/quik
2021-03-10 10:20:36.119 ERROR _logging - error: error from callback <bound method WebQuikConnector._on_socket_open of <connector.quik.WebQuikConnector.WebQuikConnector object at 0x7f3bc9e2adc0>>: _on_socket_open() takes 1 positional argument but 2 were given
q
Exit

```

**Comment by dsultanr** [comment]
думал дело в брокере, поменял все на junior.webquik.ru - ошибка та же самая

**Comment by DmitryPukhov** [comment]
Спасибо за отловленные баги!
1. **ModuleNotFoundError:** No module named 'pytrade' - залил хотфикс в master.
2.  **_on_socket_open() takes 1 positional argument but 2 were given** - там нужна версия **websocket-client** 0.57.0, я добавил Dockerfile и requirements.txt, можно в докере запустить или руками поставить **pip install -r requirements.txt**
